ExamenFinal/ExamenFinal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), 
    path('api/', include('rest_tienda.urls')),#nuevo
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #AQUI SE ESTA AGREGANDO MEDIA_URL Y MEDIA_ROOT

ExamenFinal/core/urls.py
from django.urls import path
from . import views

app_name = "CORE"

urlpatterns = [
    path('', views.producto_index, name="producto_index"),
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),
    #productos
    
    path('productos', views.productos, name="producto_productos"),

    #sign up sign in
    path('registro', views.registro, name="registro"),
    path('login', views.login, name="login"),

    #carrito
    path('carrito', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),
    path('compras', views.compras, name="carrito_compras"),
    path('compras/<int:id_compra>', views.compra_con_id, name="compra_con_id"),

    #ubi
    path('ubi', views.ubicacion, name="ubicacion"),

]

ExamenFinal/core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True, verbose_name='Id de categoria')
    nombreCategoria = models.CharField(max_length=50, verbose_name='Nombre de la Categoria')

    def __str__(self):
        return self.nombreCategoria

class Producto(models.Model):
    idProducto = models.AutoField(primary_key = True, verbose_name='Id del producto')
    nombreProducto = models.CharField(max_length=30)
    imagen = models.FileField(upload_to='productos/')
    precio = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    descuento = models.IntegerField(null=True)
    stock = models.IntegerField(null=True)
    descripcion = models.CharField(max_length=500, null=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self):
        return self.nombreProducto

class Carrito(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de carrito')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.id} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de Item carrito')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.id} | Producto: {self.producto.nombreProducto} | Carrito_id: {self.carrito.id}"

class Compra(models.Model):
    #id = models.IntegerField(primary_key=True, verbose_name='Id de compra')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="compras")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    estado = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total} | Estado:{self.estado}" 

class Compra_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE, related_name="items_compra")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.nombreProducto} | compra_id: {self.compra.id}"

class Subscripcion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="subscripcion")
    vigencia = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Id: {self.pk} | usuario_id: {self.usuario.id} | usuario: {self.usuario.username} | vigencia: {self.vigencia}"

ExamenFinal/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto
from django.contrib.auth.forms import UserCreationForm #nuevo
from django.contrib.auth.models import User #nuevo

#nuevo
class UserForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProductoForm(ModelForm):

    class Meta:
        model = Producto
        fields = ['nombreProducto', 'imagen', 'precio', 'descuento', 'stock' , 'descripcion', 'categoria']

ExamenFinal/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse
from .models import Producto
from .forms import ProductoForm
from core.models import *
from django.contrib.auth.forms import UserCreationForm #nuevo
from django.contrib.auth.models import User #nuevo
from django.contrib import messages #nuevo
# Create your views here.
def home(request):

	return render(request, 'core/home.html')

def productos(request):

    return render(request, 'core/producto/productos.html')

def login(request):

	return render(request, 'registration/login.html')

def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()

            subscripcion = Subscripcion()
            subscripcion.usuario = usuario_logeado
            subscripcion.vigencia = False
            subscripcion.save()

            return redirect(to="CORE:producto_index")
        else:
            messages.success(request, "Registro fallido. Favor reintentar")

    return render(request, 'registration/register.html')

def producto_index(request):
    productos = Producto.objects.all().order_by("-idProducto")
    
    return render(request, "core/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        #'productos' : productos[3:10] codigo para obtener solo algunos
        'productos' : productos
    })

def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(idCategoria=request.POST["categoria"])
        form = ProductoForm(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("CORE:producto_productos")
        else:
            return render(request, 'core/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, idProducto=producto_id)

    return render(request, 'core/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = get_object_or_404(Producto, idProducto=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(idCategoria=request.POST["categoria"])
        form = ProductoForm(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.nombreProducto = request.POST['nombreProducto']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.descuento = request.POST['descuento']
            producto.stock = request.POST['stock']
            producto.save()
            return redirect("CORE:producto_productos")
        else:
            return render(request, 'core/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(idProducto=producto_id)
    producto.delete()
    return redirect('CORE:producto_index')

def producto_search(request):
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(nombreProducto__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion 
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos
    })
  
def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, idCategoria = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.nombreCategoria,
    })

#funciones para el carrito

def carrito_index(request):
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        #validar si es que tiene descuento
        nuevo_precio_Carrito += (item.producto.precio - (item.producto.precio * item.producto.descuento/100))

    carrito.total = nuevo_precio_Carrito
    carrito.save()
    precio = nuevo_precio_Carrito
    if request.method == 'POST':
        compra = Compra()
        compra.usuario = usuario_logeado
        compra.total = carrito.total
        compra.estado = 'Compra realizada!'
        compra.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(idProducto=item.producto.idProducto)
            items_compra = Compra_item()
            items_compra.compra = compra
            items_compra.producto = producto
            items_compra.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(idProducto=item.producto.idProducto)
            producto.stock = producto.stock - 1
            producto.save()
        
        carrito.items.all().delete()
        carrito.total = 0
        carrito.save()

        messages.success(request, f"Compra realizada con exito!")

        return redirect('CORE:producto_index')

    return render(request, 'core/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos,
        'carrito' : carrito,
        'newprice' : precio
         
    })

def carrito_save(request):

    if request.method == 'POST':
        producto = Producto.objects.get(idProducto=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        #Agregamos el producto
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        #Sumamos el precio
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.nombreProducto} fue agregado al carrito")
        return redirect("CORE:producto_productos")

    else:
        return redirect("CORE:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    return redirect('CORE:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("CORE:carrito_index")


def compras (request):
    usuario_logeado = User.objects.get(username=request.user)
    compras = usuario_logeado.compras.all()

    return render(request, "core/carrito/compras.html",
    { 'compras' : compras })

def compra_con_id (request, id_compra):
    productos = Compra.objects.get(id=id_compra).items_compra.all()
    return render(request, 'core/carrito/compra_mostrar.html', 
    { 'productos': productos })

def ubicacion (request):

    return render(request, 'core/producto/ubicacion.html')

ExamenFinal/core/templates/core/carrito/compra_mostrar.html
{% extends "core/home.html" %}
{% block content %}
        <div class="container justify-content-md-center" style="outline: black solid 1px;  width: 100%; ">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Descuento</th>
                  </tr>
                </thead>

            {% for item in productos %}
                
                {% if item.producto.descuento > 0 %}
                <tbody> 
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{item.producto.nombreProducto.title}}</td>
                      <td>{{item.producto.precio}}</td>
                      <td>{{ item.producto.descuento }}% OFF</td>
                    </tr>
                </tbody>
                {% else %}
                <tbody> 
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{item.producto.nombreProducto.title}}</td>
                      <td>{{item.producto.precio}}</td>
                    </tr>
                </tbody>
                {% endif %}
                
            {% empty %}
                <div class="col-12 p-0 m-0">
                    <p class="d-flex justify-content-between align-items-center">
                        No tiene ningun producto en el carrito
                    </p>
                    <a href="{% url 'CORE:producto_productos' %}" class="btn btn-outline-success ">Ir a comprar</a>
                </div>
            {% endfor %}
            </table>
        </div>
{% endblock %}

ExamenFinal/core/templates/core/carrito/compras.html
{% extends "core/home.html" %}
{% load static%}
{% block content %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">ID</th>
        <th scope="col">estado</th>
        <th scope="col">total de la compra</th>
        <th scope="col"></th>
      </tr>
    </thead>
    {%for compra in compras%}
    <tbody> 
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{compra.id}}</td>
        <td>{{compra.estado}}</td>
        <td>${{compra.total}}</td>
        <td> <a style="text-decoration: none; color: black;" href="{% url 'CORE:compra_con_id' compra.id %}">ver</a> </td>
      </tr>
    </tbody>
  
        {% empty %}
            <div class="col-12 p-0 m-0">
                <p class="d-flex justify-content-between align-items-center">
                    No tiene ninguna compra realizada
                </p>
                <a href="{% url 'CORE:carrito_index' %}" class="btn btn-outline-success ">Finalizar compra</a>
            </div>
            
        {% endfor %}
</table>
{% endblock %}
<!--<div class="col-6 col-md-3 mb-4">
        <div class="card h-100 card-img-producto-home">
            <div class="card-body text-center">
                <h4 class="card-title">{{compra.estado}} </h4>
                <p class="card-text">total de la compra:    {{compra.total}} </p>
                <a href="{% url 'CORE:compra_con_id' compra.id %}">ver detalle</a>
            </div>
        </div>
    </div>-->

ExamenFinal/core/templates/core/carrito/index.html
{% extends "core/home.html" %}

{% block content %}
<main class="container my-5">
    <div class="row justify-content-center">
        <div class="col-12 mb-3">
            <h2 class="display-4 text-center text-capitalize">carrito</h2>
        </div>

        <div class="col-6 row border">

            <div class="col-12 p-0 mb-2">
                <h3 class="display-4 text-capitalize mt-2" style="font-size: 2em;">{{usuario.username.upper}}</h3>
            </div>

            {% for item in items_carrito %}
                <div class="col-12 p-0 m-0">
                    {% if item.producto.descuento > 0 %}
                        <p class="d-flex justify-content-between align-items-center">
                            {{ forloop.counter }}. {{item.producto.nombreProducto.title}} descuento {{ item.producto.descuento }}%
                            <a href="{% url 'CORE:item_carrito_delete' item.id %}" style="text-decoration: none; color: black;">eliminar</a>
                        </p>
                    {% else %}
                        <p class="d-flex justify-content-between align-items-center">
                            {{ forloop.counter }}. {{item.producto.nombreProducto.title}} 
                            <a href="{% url 'CORE:item_carrito_delete' item.id %}" style="text-decoration: none; color: black;">eliminar</a>
                        </p>
                    {% endif %}
                </div>
            {% empty %}
                <div class="col-12 p-0 m-0">
                    <p class="d-flex justify-content-between align-items-center">
                        No tiene ningun producto en el carrito
                    </p>
                    <a href="{% url 'CORE:producto_productos' %}" class="btn btn-outline-success ">Ir a comprar</a>
                </div>
            {% endfor %}

            ${{carrito.total}}


            <form method="POST">
                {% csrf_token %}
                <div class="col-12 p-0 m-0 my-3 row ">
                    <div class="col-md-5 col-lg-3 p-0">
                        <a href="{% url 'CORE:carrito_clean' %}" class="btn btn-danger btn-block">Vaciar Carrito</a>
                    </div>

                    <div class="col-12 p-0 col-md-7 col-lg-4 mt-2 mt-md-0 pl-md-3">
                        <button class="btn btn-success btn-block">Finalizar Compra</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</main>
{% endblock %}