ExamenFinal/ExamenFinal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), 
    path('api/', include('rest_tienda.urls')),#nuevo
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #AQUI SE ESTA AGREGANDO MEDIA_URL Y MEDIA_ROOT

ExamenFinal/core/urls.py
from django.urls import path
from . import views

app_name = "CORE"

urlpatterns = [
    path('', views.producto_index, name="producto_index"),
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),
    #productos
    
    path('productos', views.productos, name="producto_productos"),

    #sign up sign in
    path('registro', views.registro, name="registro"),
    path('login', views.login, name="login"),

    #carrito
    path('carrito', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),
    path('compras', views.compras, name="carrito_compras"),
    path('compras/<int:id_compra>', views.compra_con_id, name="compra_con_id"),

    #ubi
    path('ubi', views.ubicacion, name="ubicacion"),

]

ExamenFinal/core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True, verbose_name='Id de categoria')
    nombreCategoria = models.CharField(max_length=50, verbose_name='Nombre de la Categoria')

    def __str__(self):
        return self.nombreCategoria

class Producto(models.Model):
    idProducto = models.AutoField(primary_key = True, verbose_name='Id del producto')
    nombreProducto = models.CharField(max_length=30)
    imagen = models.FileField(upload_to='productos/')
    precio = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    descuento = models.IntegerField(null=True)
    stock = models.IntegerField(null=True)
    descripcion = models.CharField(max_length=500, null=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self):
        return self.nombreProducto

class Carrito(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de carrito')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.id} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de Item carrito')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.id} | Producto: {self.producto.nombreProducto} | Carrito_id: {self.carrito.id}"

class Compra(models.Model):
    #id = models.IntegerField(primary_key=True, verbose_name='Id de compra')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="compras")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    estado = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total} | Estado:{self.estado}" 

class Compra_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE, related_name="items_compra")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.nombreProducto} | compra_id: {self.compra.id}"

class Subscripcion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="subscripcion")
    vigencia = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Id: {self.pk} | usuario_id: {self.usuario.id} | usuario: {self.usuario.username} | vigencia: {self.vigencia}"

ExamenFinal/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto
from django.contrib.auth.forms import UserCreationForm #nuevo
from django.contrib.auth.models import User #nuevo

#nuevo
class UserForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProductoForm(ModelForm):

    class Meta:
        model = Producto
        fields = ['nombreProducto', 'imagen', 'precio', 'descuento', 'stock' , 'descripcion', 'categoria']

ExamenFinal/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse
from .models import Producto
from .forms import ProductoForm
from core.models import *
from django.contrib.auth.forms import UserCreationForm #nuevo
from django.contrib.auth.models import User #nuevo
from django.contrib import messages #nuevo
# Create your views here.
def home(request):

	return render(request, 'core/home.html')

def productos(request):

    return render(request, 'core/producto/productos.html')

def login(request):

	return render(request, 'registration/login.html')

def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()

            subscripcion = Subscripcion()
            subscripcion.usuario = usuario_logeado
            subscripcion.vigencia = False
            subscripcion.save()

            return redirect(to="CORE:producto_index")
        else:
            messages.success(request, "Registro fallido. Favor reintentar")

    return render(request, 'registration/register.html')

def producto_index(request):
    productos = Producto.objects.all().order_by("-idProducto")
    
    return render(request, "core/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        #'productos' : productos[3:10] codigo para obtener solo algunos
        'productos' : productos
    })

def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(idCategoria=request.POST["categoria"])
        form = ProductoForm(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("CORE:producto_productos")
        else:
            return render(request, 'core/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, idProducto=producto_id)

    return render(request, 'core/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = get_object_or_404(Producto, idProducto=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(idCategoria=request.POST["categoria"])
        form = ProductoForm(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.nombreProducto = request.POST['nombreProducto']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.descuento = request.POST['descuento']
            producto.stock = request.POST['stock']
            producto.save()
            return redirect("CORE:producto_productos")
        else:
            return render(request, 'core/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(idProducto=producto_id)
    producto.delete()
    return redirect('CORE:producto_index')

def producto_search(request):
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(nombreProducto__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion 
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos
    })
  
def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, idCategoria = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.nombreCategoria,
    })

#funciones para el carrito

def carrito_index(request):
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        #validar si es que tiene descuento
        nuevo_precio_Carrito += (item.producto.precio - (item.producto.precio * item.producto.descuento/100))

    carrito.total = nuevo_precio_Carrito
    carrito.save()
    precio = nuevo_precio_Carrito
    if request.method == 'POST':
        compra = Compra()
        compra.usuario = usuario_logeado
        compra.total = carrito.total
        compra.estado = 'Compra realizada!'
        compra.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(idProducto=item.producto.idProducto)
            items_compra = Compra_item()
            items_compra.compra = compra
            items_compra.producto = producto
            items_compra.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(idProducto=item.producto.idProducto)
            producto.stock = producto.stock - 1
            producto.save()
        
        carrito.items.all().delete()
        carrito.total = 0
        carrito.save()

        messages.success(request, f"Compra realizada con exito!")

        return redirect('CORE:producto_index')

    return render(request, 'core/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos,
        'carrito' : carrito,
        'newprice' : precio
         
    })

def carrito_save(request):

    if request.method == 'POST':
        producto = Producto.objects.get(idProducto=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        #Agregamos el producto
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        #Sumamos el precio
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.nombreProducto} fue agregado al carrito")
        return redirect("CORE:producto_productos")

    else:
        return redirect("CORE:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    return redirect('CORE:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("CORE:carrito_index")


def compras (request):
    usuario_logeado = User.objects.get(username=request.user)
    compras = usuario_logeado.compras.all()

    return render(request, "core/carrito/compras.html",
    { 'compras' : compras })

def compra_con_id (request, id_compra):
    productos = Compra.objects.get(id=id_compra).items_compra.all()
    return render(request, 'core/carrito/compra_mostrar.html', 
    { 'productos': productos })

def ubicacion (request):

    return render(request, 'core/producto/ubicacion.html')

ExamenFinal/core/templates/core/home.html
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
      integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ==" crossorigin="">
    </script>

    <title>home</title>
</head>

<body style="width: 100%; height: 100%;">
    <div class="text-center"> <div class="p-3 mb-2 bg-light text-dark" style="font-size: 40px; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">Garden Store
        <img style="width: 60px; height: 60px;" src="{% static 'core/img/plantita.png'%}" class="rounded" alt="...">
      </div> </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link " href="{% url 'CORE:producto_index' %}"> <img src="{% static 'core/img/home.png'%}" alt="..."> Inicio </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CORE:producto_productos' %}">Productos</a>
              </li>
              {% if user.is_authenticated%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CORE:carrito_compras' %}">Compras</a>
              </li>
              {% else %}
              {% endif %}
              

              {% if user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CORE:producto_create' %}">Agregar producto</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="admin/">Consola Admin</a>
              </li>
              
              {% endif %}

              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="">Bienvenido {{user.username.upper}}</b></a>
              </li>
              {% endif %}
              
            </ul>
            
            <form class="d-flex">
              {% if user.is_authenticated %}

              {% else %}
              <!--<li class="nav-item">
                <a class="nav-link" href="{% url 'CORE:registro' %}" style="color: black;"> <img src="{% static 'core/img/login.png'%}" alt="..."> Registro</a>
              </li>-->
              <a type="button" class="btn btn-outline-success my-2 my-sm-0" href="accounts/login/?next=/" style="color: black;">  <img src="{% static 'core/img/login.png' %}"> </a>
              
              {% endif %}

              <div style="padding-left: 10px;"></div>

              {% if user.is_superuser or not user.is_authenticated %}
                <button type="button" class="btn btn-outline-secondary" disabled > <img src="{% static 'core/img/cart.png'%}" alt="..."> </button>
                <!--<img style="width: 15%; height: 15%;" src="{% static 'core/img/icono.png'%}" alt="...">-->
              {% else %}
                <a type="button" class="btn btn-outline-dark my-2 my-sm-0" href="{% url 'CORE:carrito_index' %}"> <img src="{% static 'core/img/cart.png'%}" alt="..."> </a>
              {% endif %}

              <div style="padding-left: 10px;"></div>

              {% if user.is_authenticated %}
                <a type="button" class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'logout'%}?next=/"> <img src="{% static 'core/img/logout.png'%}" alt="..."> </a>
              {% endif %}
            </form>
          </div>
        </div>
      </nav>

      <!-- MENSAJES -->
      {% if messages %}
      {% for message in messages %}
          <div class="alert alert-secondary alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong> 
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      {% endfor %}
      {% endif %}
    
    <!-- DIV PARA EL CONTENIDO-->
      <div class="row" style="background-color: rgb(214, 214, 214);">
        <div class="col">
            {% block content %}
            {% endblock %}           
        </div>
      </div>

  <!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <img src="{% static 'core/img/people.png'%}"> Garden Store
          </h6>
          <p>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Redes
          </h6>
          <p>
            <a href="https://www.instagram.com/" class="text-reset"> <img src="{% static 'core/img/instagram.png'%}"> Instagram</a>
          </p>
          <p>
            <a href="https://www.facebook.com/" class="text-reset"><img src="{% static 'core/img/facebook.png'%}"> Facebook</a>
          </p>
        </div>

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><a href="{% url 'CORE:ubicacion' %}" style="text-decoration: none; color:black"><img src="{% static 'core/img/address.png'%}"> Merced 349, Santiago</a></p>
          <p>
            <img src="{% static 'core/img/mail.png' %}"> 
            garden.admin@gmail.com
          </p>
          <p><img src="{% static 'core/img/wsp.png' %}"> +569 8315 0592</p>
          <p><img src="{% static 'core/img/phone.png' %}"> +2 2371 47481</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright:
    <a class="text-reset fw-bold" href="{% url 'CORE:producto_index' %}">GardenStore.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
    <!-- Copyright
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-dark" href="{% url 'CORE:producto_index' %}">GardenStore.com</a>
    </div>Copyright -->
		

    
    <!-- Optional JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
      crossorigin="anonymous"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" 
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" 
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" 
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" 
      crossorigin="anonymous"></script>
</body>

</html>