ExamenFinal/ExamenFinal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), 
    path('api/', include('rest_tienda.urls')),#nuevo
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #AQUI SE ESTA AGREGANDO MEDIA_URL Y MEDIA_ROOT

ExamenFinal/core/urls.py
from django.urls import path
from . import views

app_name = "CORE"

urlpatterns = [
    path('', views.producto_index, name="producto_index"),
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),
    #productos
    
    path('productos', views.productos, name="producto_productos"),

    #sign up sign in
    path('registro', views.registro, name="registro"),
    path('login', views.login, name="login"),

    #carrito
    path('carrito', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),
    path('compras', views.compras, name="carrito_compras"),
    path('compras/<int:id_compra>', views.compra_con_id, name="compra_con_id"),

    #ubi
    path('ubi', views.ubicacion, name="ubicacion"),

]

ExamenFinal/core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True, verbose_name='Id de categoria')
    nombreCategoria = models.CharField(max_length=50, verbose_name='Nombre de la Categoria')

    def __str__(self):
        return self.nombreCategoria

class Producto(models.Model):
    idProducto = models.AutoField(primary_key = True, verbose_name='Id del producto')
    nombreProducto = models.CharField(max_length=30)
    imagen = models.FileField(upload_to='productos/')
    precio = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    descuento = models.IntegerField(null=True)
    stock = models.IntegerField(null=True)
    descripcion = models.CharField(max_length=500, null=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self):
        return self.nombreProducto

class Carrito(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de carrito')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.id} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='Id de Item carrito')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.id} | Producto: {self.producto.nombreProducto} | Carrito_id: {self.carrito.id}"

class Compra(models.Model):
    #id = models.IntegerField(primary_key=True, verbose_name='Id de compra')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="compras")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    estado = models.CharField(max_length=200, null=True)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total} | Estado:{self.estado}" 

class Compra_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE, related_name="items_compra")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.nombreProducto} | compra_id: {self.compra.id}"

class Subscripcion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="subscripcion")
    vigencia = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Id: {self.pk} | usuario_id: {self.usuario.id} | usuario: {self.usuario.username} | vigencia: {self.vigencia}"

ExamenFinal/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto
from django.contrib.auth.forms import UserCreationForm #nuevo
from django.contrib.auth.models import User #nuevo

#nuevo
class UserForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProductoForm(ModelForm):

    class Meta:
        model = Producto
        fields = ['nombreProducto', 'imagen', 'precio', 'descuento', 'stock' , 'descripcion', 'categoria']

ExamenFinal/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse
from .models import Producto
from .forms import ProductoForm
from core.models import *
from django.contrib.auth.forms import UserCreationForm #nuevo
from django.contrib.auth.models import User #nuevo
from django.contrib import messages #nuevo
# Create your views here.
def home(request):

	return render(request, 'core/home.html')

def productos(request):

    return render(request, 'core/producto/productos.html')

def login(request):

	return render(request, 'registration/login.html')

def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()

            subscripcion = Subscripcion()
            subscripcion.usuario = usuario_logeado
            subscripcion.vigencia = False
            subscripcion.save()

            return redirect(to="CORE:producto_index")
        else:
            messages.success(request, "Registro fallido. Favor reintentar")

    return render(request, 'registration/register.html')

def producto_index(request):
    productos = Producto.objects.all().order_by("-idProducto")
    
    return render(request, "core/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        #'productos' : productos[3:10] codigo para obtener solo algunos
        'productos' : productos
    })

def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(idCategoria=request.POST["categoria"])
        form = ProductoForm(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("CORE:producto_productos")
        else:
            return render(request, 'core/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, idProducto=producto_id)

    return render(request, 'core/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = get_object_or_404(Producto, idProducto=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(idCategoria=request.POST["categoria"])
        form = ProductoForm(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.nombreProducto = request.POST['nombreProducto']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.descuento = request.POST['descuento']
            producto.stock = request.POST['stock']
            producto.save()
            return redirect("CORE:producto_productos")
        else:
            return render(request, 'core/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'core/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(idProducto=producto_id)
    producto.delete()
    return redirect('CORE:producto_index')

def producto_search(request):
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(nombreProducto__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion 
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos
    })
  
def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, idCategoria = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'core/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.nombreCategoria,
    })

#funciones para el carrito

def carrito_index(request):
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        #validar si es que tiene descuento
        nuevo_precio_Carrito += (item.producto.precio - (item.producto.precio * item.producto.descuento/100))

    carrito.total = nuevo_precio_Carrito
    carrito.save()
    precio = nuevo_precio_Carrito
    if request.method == 'POST':
        compra = Compra()
        compra.usuario = usuario_logeado
        compra.total = carrito.total
        compra.estado = 'Compra realizada!'
        compra.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(idProducto=item.producto.idProducto)
            items_compra = Compra_item()
            items_compra.compra = compra
            items_compra.producto = producto
            items_compra.save()

        for item in carrito.items.all():
            producto = Producto.objects.get(idProducto=item.producto.idProducto)
            producto.stock = producto.stock - 1
            producto.save()
        
        carrito.items.all().delete()
        carrito.total = 0
        carrito.save()

        messages.success(request, f"Compra realizada con exito!")

        return redirect('CORE:producto_index')

    return render(request, 'core/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos,
        'carrito' : carrito,
        'newprice' : precio
         
    })

def carrito_save(request):

    if request.method == 'POST':
        producto = Producto.objects.get(idProducto=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        #Agregamos el producto
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        #Sumamos el precio
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.nombreProducto} fue agregado al carrito")
        return redirect("CORE:producto_productos")

    else:
        return redirect("CORE:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    return redirect('CORE:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("CORE:carrito_index")


def compras (request):
    usuario_logeado = User.objects.get(username=request.user)
    compras = usuario_logeado.compras.all()

    return render(request, "core/carrito/compras.html",
    { 'compras' : compras })

def compra_con_id (request, id_compra):
    productos = Compra.objects.get(id=id_compra).items_compra.all()
    return render(request, 'core/carrito/compra_mostrar.html', 
    { 'productos': productos })

def ubicacion (request):

    return render(request, 'core/producto/ubicacion.html')

ExamenFinal/core/templates/core/producto/create.html
{% extends 'core/home.html' %}
{% load static %}
{% block content %}
<div class="row">

    <!-- MENSAJE DE ERROR -->
    {% if error_message %}
    <div class="row">
        <div class="col">
            <strong>{{ error_message }}</strong>
        </div>
    </div>
    {% endif %}
    <div class="col"> 
        <!-- TITULO -->
        <div class="container justify-content-md-center">
            <h2 class="text-uppercase text-center">Agregar producto</h2>
        </div>

        <!-- FORMULARIO -->
        <div class="container justify-content-md-center" style="outline: black solid 1px;  width: 100%; ">
            <form action="{% url 'CORE:producto_create' %}" method="post" enctype="multipart/form-data">
            
            {% csrf_token %}
            
            <!-- NOMBRE PRODUCTO -->
                <div >
                    <label for="nombreProducto">Nombre del producto</label>
                    <input style="width: 50%;" class="form-control" type="text" name="nombreProducto" placeholder="" required>
                </div>
                <br>
                <!-- IMAGEN -->
                <div>
                    <div class="form-group">
                        <label for="imagen">Imagen producto</label>
                        <input type="file" class="form-control-file" name="imagen" id="imagen"
                            placeholder="Ingrese la imagen..." required>
                    </div>
                </div>
                <br>
                    <!-- CATEGORIA -->
                <div>
                    <select class="custom-select" name="categoria" required>
                        <option value="" selected>Categoria del producto</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.idCategoria }}">{{ categoria.nombreCategoria }}</option>
                        {% endfor %}
                    </select>
                </div>
                <br>
                    <!-- DESCRIPCION -->
                    <div>
                        <textarea class="form-control" name="descripcion" rows="3" style="width: 50%;" required></textarea>
                    </div>
                    <br>
                    <br>
                    <div >
                        <!-- PRECIO -->
                        <div >
                            <div >Precio: $</div>
                            <input style="width: 50%;" type="float" class="form-control" name="precio" placeholder="$000.00" required>
                        </div>
                        <div >
                            <div >Stock</div>
                            <input style="width: 50%;" type="integer" class="form-control" name="stock" placeholder="" required>
                        </div>
                        <div >
                            <div >Descuento: </div>
                            <input style="width: 50%;" type="integer" class="form-control" name="descuento" placeholder="%" required>
                        </div>
                        <br>
                        <br>
                        <!-- BOTON -->
                        <div >
                            <button type="submit" class="btn btn-outline-dark btn-block"> <img src="{% static 'core/img/add.png'%}">Agregar</button><br><br>
                        </div>
                    </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ExamenFinal/core/templates/core/producto/edit.html
{% extends 'core/home.html' %}

{% block content %}
<section class="row my-5 container mx-auto">

    {% if error_message %}
        <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
            <strong>{{ error_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if okey_message %}
        <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
            <strong>{{ okey_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="col-12">
        <h3>Editar producto</h3>
    </div>

    <form action="" method="post" enctype="multipart/form-data" class="w-100 col-12">

        {% csrf_token %}
        <div class="col-12 p-0 form-group">
            <input class="form-control" type="text" name="nombreProducto" placeholder="Ingrese el nombre del producto..." value="{{producto.nombreProducto.title}}" required>
        </div>

        <div class="row container mx-auto p-0 pt-3">
            <div class="col-md-6 p-0 m-0">
                <div class="form-group"><!--Aqui falta agregar que al momento de editar nos cargue la foto que ya teniamos cargada-->
                    <label for="imagen">Imagen producto</label>
                    <input type="file" class="form-control-file" name="imagen" id="imagen"
                     placeholder="Ingrese la imagen..." required>
                </div>
            </div>

            <div class="col-md-6 p-0 m-0 row">
                <div class="col-12 p-0 form-group">
                    <select class="custom-select" name="categoria" required>
                        <option value="" selected>-- Seleccione la categoria --</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.idCategoria }}">{{ categoria.nombreCategoria }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-12 p-0 form-group mb-3">
                    <textarea class="form-control" name="descripcion" rows="3" required>{{producto.descripcion.capitalize}}</textarea>
                </div>

                <div class="col-12 ">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-auto m-0 p-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">Precio: $</div>
                                </div>
                                <input type="float" class="form-control" name="precio" placeholder="XXXX.XX" value="{{ producto.precio|floatformat }}" required>
                            </div>
                        </div>
                        
                        <div class="col-auto m-0 p-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">Descuento: </div>
                                </div>
                                <input type="integer" class="form-control" name="descuento" placeholder="%" value="{{ producto.descuento|floatformat }}" required>
                            </div>
                        </div>
                        
                    </div>
                </div>

                <div class="col-12 ">
                    <div class="row justify-content-between align-items-center">
                        <div class="col-auto m-0 p-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">Editar stock: </div>
                                </div>
                                <input type="integer" class="form-control" name="stock" placeholder="unidades" value="{{ producto.stock }}" required>
                            </div>
                        </div>
                        <br><br>
                        <div class="form-group col-md-4 col-lg-3 m-0 p-0 mt-2 mt-lg-0">
                            <button type="submit" class="btn btn-success btn-block">Editar</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>

</section>
{% endblock %}

ExamenFinal/core/templates/core/producto/index.html
{% extends "core/home.html" %}

{% load static %}

{% block content %}

<div class="container">
  <!--<div>
        <img src="{% static 'core/img/flor3.jpg'%}" class="rounded" alt="...">
    </div>-->
  <div id="carouselExampleControls" style="width: 90%;" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'core/img/1.png'%}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'core/img/2.png'%}" class="d-block w-100" alt="...">
          </div>
          <!--<div class="carousel-item">
            <img src="..." class="d-block w-100" alt="...">
          </div>-->
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    

</div>


{% endblock %}

ExamenFinal/core/templates/core/producto/productos.html
{% extends "core/home.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="card" style="width: 18rem;">
            <img style="width:100%; height:100%" src="{% static 'core/img/flor.png'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Flores</h5>
                <a href="{% url 'CORE:productos_por_categoria' 4%}" class="btn btn-secondary">Ir a flores</a>
            </div>
        </div>

        <div class="card" style="width: 18rem;">
            <img style="width:100%; height:100%" src="{% static 'core/img/arbusto.webp'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Arbustos</h5>
                <a href="{% url 'CORE:productos_por_categoria' 3%}" class="btn btn-secondary">Ir a arbustos</a>
            </div>
        </div>

        <div class="card" style="width: 18rem;">
            <img style="width:100%; height:100%" src="{% static 'core/img/macetero.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Maceteros</h5>
                <a href="{% url 'CORE:productos_por_categoria' 1%}" class="btn btn-secondary">Ir a maceteros</a>
            </div>
        </div>

        <div class="card" style="width: 18rem;">
            <img style="width:100%; height:100%" src="{% static 'core/img/tierrahoja.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Tierras</h5>
                <a href="{% url 'CORE:productos_por_categoria' 2%}" class="btn btn-secondary">Ir a tierras</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ExamenFinal/core/templates/core/producto/search.html
{% extends "core/home.html" %}
{% load static%}
{% block content %}
<div class="row mt-5">

    <div class="row row-cols-1 row-cols-md-3 container justify-content-center">
        {% for producto in productos %}
        <div class="col-6 col-md-4 col-lg-3 mb-4">

            <div class="card" style="width: 80%;">
                <img style="width:100%; height:100%" src="{{MEDIA_URL}}{{producto.imagen.url}}" class="card-img-top"
                    alt="...">
                
                <div class="card-body">
                    {% if producto.descuento > 0 %}
                        <h5 class="card-title">{{ producto.nombreProducto.title|truncatechars:30 }}</h5>
                        <p class="card-text ">${{ producto.precio|truncatechars:50 }} <br> descuento    : {{producto.descuento}}%</p>
                        {% if producto.stock < 10 %}
                        <p class="card-text " style="color: rgb(126, 126, 126);"> Pocas unidades disponibles</p>
                        {% else %}

                        {% endif %}
                        <a href="{% url 'CORE:producto_show' producto.idProducto %}"
                        class="btn btn-outline-success btn-block">Ver</a>
                    {% else %}
                        <h5 class="card-title">{{ producto.nombreProducto.title|truncatechars:30 }}</h5>
                        <p class="card-text ">${{ producto.precio|truncatechars:50 }}</p>
                        {% if producto.stock < 10 %}
                        <p class="card-text " style="color: rgb(126, 126, 126);"> Pocas unidades disponibles</p>
                        {% else %}

                        {% endif %}
                        <a href="{% url 'CORE:producto_show' producto.idProducto %}"
                        class="btn btn-outline-success btn-block">Ver</a>
                    {% endif %}
                    <div style="padding-bottom: 5px;"></div>
                    <form action="{% url 'CORE:carrito_save' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="producto_id" value="{{ producto.idProducto }}">
                        {% if user.is_superuser or not user.is_authenticated %}
                        <button type="submit" class="btn btn-outline-secondary" disabled>Agregar al carrito</button>
                        {% elif producto.stock <= 0 %}
                        <button type="submit" class="btn btn-outline-secondary" disabled>Agregar al carrito</button>
                        {% else %}
                        <button type="submit" class="btn btn-outline-success">Agregar al carrito </button>
                        {% endif %}
                    </form>
                    {% if user.is_superuser %}
                    <a href="{% url 'CORE:producto_edit' producto.idProducto %}"
                        class="btn btn-outline-dark btn-block"><img src="{% static 'core/img/edit.png'%}"></a>
                    <a href="{% url 'CORE:producto_delete' producto.idProducto %}"
                        class="btn btn-outline-danger btn-block"><img src="{% static 'core/img/delete.png'%}"></a>
                    {% endif %}
                </div>
            </div>

        </div>
        {% empty %}
        <h2 class="col-12 display-4 text-center mt-5" style="font-size: 2em; height: 30vh;">No hay productos que
            coincidan</h2>
        {% endfor %}

    </div>
</div>
{% endblock %}

ExamenFinal/core/templates/core/producto/show.html
{% extends "core/home.html" %}
{% load static %}
{% block content %}
<div class="row my-5 container">

    <div class="col-10 mx-auto">
        <div class="row border">

            <div class="col-md-5 p-0 ">
                <img style="width: 100%; height: 100%;" src="{{MEDIA_URL}}{{producto.imagen.url}}" alt="">
            </div>

            <div class="col-md-7 p-4 d-flex flex-column justify-content-between">
                <div class="detalle-producto-content__text">
                    <h1 class="display-5 text-capitalize">{{ producto.nombreProducto }}</h1>

                    <!--<h2 class="display-7 text-capitalize mb-3">Categoria: {{ producto.categoria.nombreCategoria }}</h2>-->

                    <p>{{ producto.descripcion.capitalize }}</p>
                    <p><b>Categoria: </b> {{ producto.categoria.nombreCategoria }}</p>
                    <p><b> Stock: </b> {{ producto.stock}}</p>
                    <p class="m-0">
                        <strong>Precio:</strong>
                        ${{ producto.precio }}
                    </p>
                </div>

                <div class="d-flex justify-content-between align-items-center">
                    
                    <form action="{% url 'CORE:carrito_save' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="producto_id" value="{{ producto.idProducto }}">
                        {% if user.is_superuser or not user.is_authenticated %}
                            <button type="submit" class="btn btn-outline-secondary" disabled><img src="{% static 'core/img/cart.png' %}">Agregar al carrito</button>
                        {% elif producto.stock <= 0 %}
                            <button type="submit" class="btn btn-outline-secondary" disabled><img src="{% static 'core/img/cart.png' %}">Agregar al carrito</button>
                        {% else %}
                            <button type="submit" class="btn btn-outline-success"><img src="{% static 'core/img/cart.png' %}">Agregar al carrito</button>
                        {% endif %}
                    </form>
                </div>
            </div>

        </div>
    </div>

</div>
{% endblock %}